Create 0xfB7Eb1FCe8fC2Fa1F84d962191931394003C7557.setdetails.json
SetProtocol/uniswap-tokenlist pull request #65
Opened 2021-07-05 11:35 UTC by Keanuji

ErosAM JediFund

When submitting a new or existing set details change, make sure you have followed the following steps:

### Adding New Set Details
- [ ]  Add a new file (or update existing file) into the `set-details` folder that is named as `[insert-your-set-address].setdetails.json` (i.e. 0x1494CA1F11D487c2bBe4543E90080AeBa4BA3C2b.setdetails.json). Make sure to provide the [checksum address](https://ethsum.netlify.app/) for your Set
- [ ] Verify the JSON follows the correct schema according to this [template](https://github.com/SetProtocol/uniswap-tokenlist/blob/main/set-details.schema.json). You can verify it by pasting the schema into this [schema validator](https://www.jsonschemavalidator.net) and checking if your input JSON matches properly. If you need to have multi-line JSON, you can use a HJSON converter to help with writing it and then paste in the final valid JSON spit out from it (see README for example)
- [ ] If adding brand new token, make sure to add it to the set.tokenlist.json as well following the correct schema from Uniswap: https://github.com/Uniswap/token-lists/blob/master/src/tokenlist.schema.json

### Updating Existing Set Details
- [ ] If updating existing set details, update the version number appropriately (see the JSON schema above for version numbering explanation).
- [ ] When generating a signature, make sure the version signed is for the one reflected in the version details for your entry.

### Signature (Required)

- [ ] Attach the proper signature. You can generate one by going to the page for your Set on TokenSets and signing in. Tap on your Set's name and follow the instructions provided (i.e. 0x21fbf0696d5e0aa2ef41a2b4ffb623bcaf070461d61cf7251c74161f82fec3a4370854bc0a34b3ab487c1bc021cd318c734c51ae29374f2beb0e6f2dd49b4bf41c):

[ATTACH SIGNATURE HERE]

2021-07-05 17:14 UTC, asoong commented on set-details/0xfB7Eb1FCe8fC2Fa1F84d962191931394003C7557.setdetails.json
> +    "managerIcon": "https://i.imgur.com/RzlGGQg.png",
Can you download a copy and add it to the directory so we can maintain the loading? Don't want imgur to become a dependency

2021-07-05 19:07 UTC, Keanuji commented
Done

Thanks !

Le lun. 5 juil. 2021 à 19:14, Alex Soong ***@***.***> a
écrit :

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In set-details/0xfB7Eb1FCe8fC2Fa1F84d962191931394003C7557.setdetails.json
> <https://github.com/SetProtocol/uniswap-tokenlist/pull/65#discussion_r664058993>
> :
>
> > @@ -0,0 +1,14 @@
> +{
> +  "setDetails": {
> +    "chainId": 1,
> +    "setName": "JediFund",
> +    "setSymbol": "TX3",
> +    "setDecimals": 18,
> +    "setDescription": "JediFund is our high-growth fund, seeking to invest in future leader crypto projects that we believe can grow at exceptional rates and provide outsized returns while keeping risk at a minimum over the long term.",
> +    "website": "https://www.erosam.com",
> +    "managerName": "Eros Asset Management",
> +    "managerIcon": "https://i.imgur.com/RzlGGQg.png",
>
> Can you download a copy and add it to the directory so we can maintain the
> loading? Don't want imgur to become a dependency
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SetProtocol/uniswap-tokenlist/pull/65#pullrequestreview-699340883>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO7DRYN3CWHFXX2ZIBG4HDLTWHSAXANCNFSM472RU6TQ>
> .
>

2021-07-21 05:11 UTC, asoong commented on set-details/0xfB7Eb1FCe8fC2Fa1F84d962191931394003C7557.setdetails.json
> +    "setIcon": "https://github.com/Keanuji/QindoNM/blob/main/1200px-Eros._(Greek_mythology_systematized).png",
Can you check this into our repository? Don't want to be referencing another repository

2021-08-03 22:34 UTC, adityachoubeyy commented
Aditya.choubey53@gmail.com

2021-08-03 22:36 UTC, adityachoubeyy approved these changes

2021-08-03 22:38 UTC, adityachoubeyy approved these changes
Aditya.choubey53@gmail.com

2021-08-03 22:39 UTC, adityachoubeyy commented
Aditya.choubey53@gmail.com

2021-08-03 22:54 UTC, adityachoubeyy commented
Trur

2021-08-03 22:59 UTC, adityachoubeyy requested changes
Aditya.choubey53@gmail.com

2021-08-14 08:17 UTC, adityachoubeyy commented on set-details/0xfB7Eb1FCe8fC2Fa1F84d962191931394003C7557.setdetails.json
> +    "managerIcon": "https://i.imgur.com/RzlGGQg.png",
Sure

2021-10-03 20:55 UTC, justinkchen commented
Closing due to inactivity

2021-10-03 20:55 UTC, closed without merging